- name: Deploy Catalogue Service
  hosts: catalogue
  become: yes
  tasks:

  - name: Disable old Node.js and enable Node.js 18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install Node.js
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp/catalogue.zip

  - name: Extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install node dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copy catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Reload systemd and start catalogue service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Copy MongoDB repo file
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install MongoDB shell
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: Get product count from catalogue DB
    ansible.builtin.command: mongo --host mongodb.devopstraining.space --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  - name: Debug - Show product count
    ansible.builtin.debug:
      msg: "Product count in DB: {{ product_count.stdout | trim }}"

  - name: Load catalogue data if not present
    ansible.builtin.command: mongo --host mongodb.devopstraining.space < /app/schema/catalogue.js
    when: product_count.stdout | trim == "0"

  - name: Enable and start catalogue service
    ansible.builtin.service:
      name: catalogue
      enabled: yes
      state: started
